model_list:
  - model_name: openai/gpt-oss-20b:free
    litellm_params:
      model: openrouter/openai/gpt-oss-20b:free
      api_key: os.environ/OPENAI_API_KEY
      api_base: https://openrouter.ai/api/v1

  - model_name: nvidia/nemotron-3-super-120b-a12b:free
    litellm_params:
      model: openrouter/nvidia/nemotron-3-super-120b-a12b:free
      api_key: os.environ/OPENAI_API_KEY
      api_base: https://openrouter.ai/api/v1

  - model_name: openai/gpt-oss-120b:free
    litellm_params:
      model: openrouter/openai/gpt-oss-120b:free
      api_key: os.environ/OPENAI_API_KEY
      api_base: https://openrouter.ai/api/v1

  - model_name: meta-llama/llama-3.3-70b-instruct:free
    litellm_params:
      model: openrouter/meta-llama/llama-3.3-70b-instruct:free
      api_key: os.environ/OPENAI_API_KEY
      api_base: https://openrouter.ai/api/v1

  - model_name: google/gemma-3-27b-it:free
    litellm_params:
      model: openrouter/google/gemma-3-27b-it:free
      api_key: os.environ/OPENAI_API_KEY
      api_base: https://openrouter.ai/api/v1

router_settings:
  fallbacks:
    - openai/gpt-oss-20b:free:
        - nvidia/nemotron-3-super-120b-a12b:free
        - openai/gpt-oss-120b:free
        - meta-llama/llama-3.3-70b-instruct:free

litellm_settings:
  drop_params: true
